# Ansible role for deploy the Nginx for the Create Go App project.
# Author: Vic Shóstak <koddr.me@gmail.com> (https://github.com/koddr)
# For more information, please visit https://github.com/create-go-app/cli

---
#
# Delete webserver files.
#
- name: Delete previous webserver files
  file:
    state: absent
    path: "{{ server_dir }}/webserver"

#
# Create folder for Nginx.
#
- name: Ensures Nginx dir exists
  file:
    state: directory
    path: "{{ server_dir }}/webserver"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"

#
# Create Nginx config.
#
- name: Adding nginx.conf file
  template:
    src: nginx.conf.j2
    dest: "{{ server_dir }}/webserver/nginx.conf"
    mode: 0600

#
# Create default server config.
#
- name: Adding default.conf file
  template:
    src: "{{ 'default-https.conf.j2' if nginx_use_only_https == 'yes' else 'default-http.conf.j2' }}"
    dest: "{{ server_dir }}/webserver/default.conf"
    mode: 0600

#
# Run official Nginx Docker container (for HTTP only) with specified version.
#
- name: Run Nginx container (for HTTP)
  community.docker.docker_container:
    name: cgapp-nginx
    image: "nginx:{{ nginx_version }}"
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "80:80"
    volumes:
      - "{{ server_dir }}/webserver/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ server_dir }}/webserver/default.conf:/etc/nginx/conf.d/default.conf"
  when: nginx_use_only_https == 'no'

#
# Run official Nginx Docker container (for HTTPS only) with specified version.
#
- name: Run Nginx container (for HTTPS only)
  community.docker.docker_container:
    name: cgapp-nginx
    image: "nginx:{{ nginx_version }}"
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ server_dir }}/webserver/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ server_dir }}/webserver/default.conf:/etc/nginx/conf.d/default.conf"
  when: nginx_use_only_https == 'yes'
