FROM node:14-alpine AS builder

LABEL maintainer="Vic Shóstak <truewebartisans@gmail.com>"

# Go to work directory.
WORKDIR /build

# Copy all needed files to /build folder.
COPY package*.json src ./

# Install frontend dependencies and run build.
RUN npm ci -s --only=production && npm run build

FROM scratch

# Copy builded files to container root.
COPY --from=builder /build/dist /